# https://travis-ci.org/boardcam/BoardCAM

dist: xenial
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - pytest
  - python boardcam.py
#  - coverage run tests/test_points.py

# Push the results back to codecov
#after_success:
#  - codecov